### ISSUE TITLE
What is the purpose of `ava/init`

### ISSUE THREAD

**Issue by andreGarvin** [avajs/ava-init#10]
Hey, I was looking at the npm install stdout and saw that it said `Please use @ava/init instead`. I was curious about why it was telling me to do,  what is the difference between the two cause I do not see one but also what is repo is about ?

**Comment by novemberborn** [comment]
It powers the `ava --init` command, which we're [in the process of removing](https://github.com/avajs/ava/pull/1738). That also removes the dependency from AVA itself. Hopefully the README here covers that well enough.

I realized the deprecation message isn't particularly helpful since folks aren't likely to have a direct dependency on `ava-init`, so I've removed it. Thank you for that realization!
